### ISSUE TITLE
Fix the timestamp date

### ISSUE THREAD

**Issue by andremacola** [imFORZA/wp-queue#24]
I think the schedule needs to be improved. With other datezones the wp-queue does not work as espected. Maybe getting the timezone from wordpress configuration.

The line: `gmdate( 'Y-m-d H:i:s', $timestamp );`

**Comment by bhubbard** [comment]
@andremacola Where do you see this line?

**Comment by andremacola** [comment]
I'm closing this issue. It was a server side problem dealing with dates.
